### ISSUE TITLE
Feature Request: Global Styling

### ISSUE THREAD

**Issue by AnExiledDev** [Spjak/DungeonsAndMarkdown#1]
This might already be available, and I'm unaware, but I'd love the ability to have a global-style file that would apply to all previews within the project. I moved away from the homebrewer because it was easier to write the markdown in vscode, and track all of the elements of larger projects, but I used extensive custom styling, which I'd rather not copy and paste per page. As in vscode I have different concepts in different .md files and folders instead of 1 single page, which is easier for me to manage, and all that's missing is the global styling, as far as I can tell.

I was so sad when I found the old project had been abandoned, thank you so much for picking this up again, it's amazing!

**Comment by Spjak** [comment]
I'm happy to hear you are enjoying the extension!

There is no feature for global styling at the moment, but it sounds like very reasonable thing to add and it should not be too difficult.
There will be a little work to ensure the preview and the generated html both work with local files, since the preview has strict limits on loading files from disk.

Do you have an example of a custom style sheet file that I can use for testing, to make sure it actually works the way you describe?

**Comment by AnExiledDev** [comment]
Sure, one of my more refined versions can be found here https://homebrewery.naturalcrit.com/share/y7W0KWFQHFo-

I've copy-pasted the contents into a single file, then copy-pasted all of the styling into a style tag. I only found 2 deviations between how Homebrewery and this extension processes the styling and adjusted those (marked by the EXT BUG comments) but other than that everything displays correctly in the preview after the 2 corrections.

Let me know if I can help with anything else, thanks!

EDIT: Would you like me to create separate issues for styling that deviates, even minimally, from the Homebrewery for the ones I have found and future issues?

**Comment by Spjak** [comment]
That looks very cool!
I can see why you would not want all of that styling in every document.

I have added a configuration setting that enables you to add one or more css files as custom styling for everything in the workspace and tested with your styling - it seems to work.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/13364308/223471208-d5f2f2b1-757c-424f-b2d6-6cce3e45cea9.png">

I will push an update later this week.

Regarding the 2 bugs, those are caused by some style customization I have added on top of what Homebrewery generates, because VSCode in Dark theme would overwrite certain styling (such as font color).
I will have to dig a little further to see if I can make the VSCode webview behave without this, so it doesn't interfere with custom styling.
For now, I'll add it to known issues to make it clear where there could be differences.
