### ISSUE TITLE
Feature Request: Homebrewery-specific Syntax Highlighting

### ISSUE THREAD

**Issue by DigitalCommodore** [Spjak/DungeonsAndMarkdown#2]
It would be nice if the extension would show the same sort of highlighting that can be found on the homebrewery site. In particular, items such as:

{{pageNumber 2}}
{{footnote PART 2 | BORING STUFF}}

and 

\page

\column

etc.

**Comment by DigitalCommodore** [comment]
![image](https://user-images.githubusercontent.com/28689205/223231189-638ab516-cbd5-43ba-82f7-e8cbb87b4691.png)

**Comment by Spjak** [comment]
That is a good idea!
Since the files are written in Markdown, it would require extending that language in VSCode, which _should_ be possible.
I'm not sure it will be possible to make it look exactly as on the website (particularly for something like the \page), but most of the syntax highlighting looks simple enough.

**Comment by Spjak** [comment]
Finally got around to finishing something.
I can't do all the highlighting they have on the website, mainly because it would clash with the existing Markdown syntax highlighting, but I did add most of the easy ones and it should cover most of your examples as well.

Since I don't control the actual colors (they depend on which theme you use), I had to pick some types for the various syntax highlights.
I did this based on the Dark theme, mainly because it's the one I use and secondarily because I couldn't get the colors I wanted with the Light theme.

![syntax-example](https://user-images.githubusercontent.com/13364308/231229438-f1ab4592-688a-4cba-8aad-c2c8c0e720f3.png)
![syntax-example-light](https://user-images.githubusercontent.com/13364308/231229441-decce255-6977-41c9-986e-8cf7429853c2.png)
